baseurl = ""
languageCode = "en"
title = "kshlm's blog"

theme = "PaperMod"

paginate = 10
enableRobotsTXT = true
enableEmoji  = true

buildDrafts = false
buildFutures = false
buildExpired = false

[params]
  env = "production"
  description = "My (very) rarely updated blog about nothing in particular"

  comments = false
  ShowReadingTime = true
  ShowShareButtons = false
  defaultTheme = "auto"
  disableThemeToggle = false
  disableSpecial1stPost = true

[params.assets]
  favicon = "/favicon.png"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[params.label]
  #icon = "/apple-touch-icon.png"
  #iconHeight = 32

[params.profileMode]
  enabled = true
  title = "kshlm's blog"
  subtitle = "My (very) rarely updated blog about nothing in particular"
  image = "/apple-touch-icon.png"
  imageWidth = 120
  imageHeight = 120

[[params.profileMode.buttons]]
  name = "About"
  url = "/about/"

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/post/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/kshlm"

[[params.socialIcons]]
  name = "keybase"
  url = "https://keybase.io/kshlm"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/kshlmster"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/kshlmster"

[params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = false

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
