baseurl = "https://kshlm.in/"
languageCode = "en-us"
title = "kshlm's blog"
theme = "angels-ladder"
googleAnalytics = "UA-50804986-2"
pygmentsCodeFences = true
pygmentsUseClasses = true

[permalinks]
  post = "/:slug"
  page = "/:slug"

[[menu.main]]
  name = "About Me"
  url = "/about/"

[params]
  subtitle = "My (very) rarely update blog about nothing in particular"
  author = "Kaushal M"
  favicon = "favicon.png"
  languageCode = "en"

  github = "https://github.com/kshlm/"
  twitter = "https://twitter.com/kshlm/"
  facebook = "https://facebook.com/kshlmster/"
  gplus = "https://plus.google.com/+KaushalMadappa"
  linkedin = "https://in.linkedin.com/in/kshlmster"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"
  category = "categories"
