name: Build gh-pages

on:
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@master
      with:
        lfs: true
    - name: Setup hugo
      run: echo Hello, world!
    - name: Run a multi-line script
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        hugo-version: 0.56.2
        extended: true
    - name: Build
      run: |
        hugo --minify
        echo "kshlm.in" > public/CNAME
        cp -a .forestry/admin public
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
