name: Build gh-pages

on:
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@master
      with:
        lfs: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        hugo-version: 0.56.2
        extended: true
    - name: Build site
      run: |
        hugo --minify
        echo "kshlm.in" > public/CNAME
        cp -a .forestry/admin public
    - name: Deploy to kshlm.github.com
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        REPOSITORY_NAME: kshlm/kshlm.github.io
        BRANCH: master
        FOLDER: public
